version: "3"

services:
  hishab-backend:
    container_name: hishab-backend-dev
    restart: unless-stopped

    ports:
      - "4000:4000"
      - "5555:5555"

    build:
      context: ./turbo
      dockerfile: Dockerfile-dev

    working_dir: /hishab/turbo/apps/hishabBackend
    command: sh -c "npx prisma migrate dev && yarn dev"

    volumes:
      - ./turbo/:/hishab/turbo
