FROM node:16-alpine3.12 AS build

RUN apk update && apk upgrade
RUN apk add alpine-sdk libffi-dev openssl-dev build-base gcc wget git
RUN apk add --virtual build-dependencies
RUN apk add curl make musl-dev go

WORKDIR /hishab/turbo